feat(bob): add `concurrent` and `failFast` config options
callstack/react-native-builder-bob pull request #194
Opened 2021-09-06 09:14 UTC by LukeeeeBennett

### Summary

### Test plan

2021-09-07 07:36 UTC, lbennett-simplestream approved these changes

2021-09-27 20:05 UTC, Krizzu approved these changes
Great idea to speed those builds 👍🏼

2021-09-27 20:05 UTC, Krizzu commented on packages/react-native-builder-bob/src/index.ts
> +        logger.warn('Concurrency is disabled. Ignoring failFast.');
Great 👍🏼

2021-09-27 23:14 UTC, satya164 requested changes

2021-09-27 23:14 UTC, satya164 commented on README.md
> +
Is there any reason to provide options for these instead of making the builds work that way by default?

2021-09-27 23:14 UTC, satya164 commented on packages/react-native-builder-bob/src/index.ts
> +        : Promise.allSettled(promises));
I assume the logs will be out of order this way. Can you verify if the logs are still working correctly and properly grouped?

2022-06-20 11:12 UTC, satya164 commented
Hello @LukeeeeBennett, lemme know what you think about my comments

2022-10-23 15:53 UTC, satya164 commented
Closing due to no reponse. Please open a new Pr if you still want to get this merged.

2022-10-23 15:53 UTC, closed without merging