Add abiFilters to the native template
callstack/react-native-builder-bob pull request #546
Opened 2024-04-11 14:39 UTC by j-piasecki

### Summary

In the native template `abiFilters` is missing from `externalNativeBuild` block. This means that the library would be built for every available ABI when building the application, even if the application itself is being built for a specific one. This is not that problematic (besides taking more time) when using React Native aar, but when building RN from source the core `.so` files will be built for that specific ABI. In case the library depends on a `.so` file, it would fail at the linking stage due to missing `.so` for the remaining ABIs.

### Test plan
See
- https://github.com/Expensify/App/pull/40102
- https://github.com/Expensify/react-native-live-markdown/pull/284
- https://github.com/margelo/react-native-quick-sqlite/pull/41

2024-04-26 10:23 UTC, atlj approved these changes

2024-05-08 15:51 UTC, tomekzaw commented
@atlj Looks like all CIs failed because of `Java heap space`, can you please re-run failed jobs?

2024-05-16 10:14 UTC, satya164 requested changes

2024-05-16 10:14 UTC, satya164 commented on packages/create-react-native-library/templates/native-common/android/build.gradle
> +  def value = project.getProperties().get("reactNativeArchitectures")
Shouldn't this be `rootProject`?

```suggestion
  def value = rootProject.getProperties().get("reactNativeArchitectures")
```

2024-05-16 10:16 UTC, satya164 commented
@tomekzaw seems it's failing for all of the Android builds so it doesn't seem like flaky tests but an issue with the change.

2024-05-16 11:42 UTC, merged